#!/bin/bash

##
## Installs a list of my prefered brew tools.
##
## Install:
## ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
##
## http://mxcl.github.com/homebrew/
##

brew install coreutils 
brew install aircrack-ng 
brew install arping 
brew install htop 
brew install jed 
brew install john 
brew install imagemagick 
brew install nmap 
brew install pwgen
brew install rhino 
brew install scala 
brew install unrar 
brew install wget 
brew install wireshark 
